-- Translates an IP from 1234567890 to "73.150.2.210"
DROP FUNCTION IF EXISTS decodeIP;
CREATE FUNCTION decodeIP (ip INT UNSIGNED)
RETURNS CHAR(15) DETERMINISTIC
RETURN CONCAT_WS(".", ip DIV 16777216, ip DIV 65536 MOD 256, ip DIV 256 MOD 256, ip MOD 256);
-- Translates an IP from (73, 150, 2, 210) to 1234567890
DROP FUNCTION IF EXISTS encodeIP;
CREATE FUNCTION encodeIP (ip8 INT, ip16 INT, ip24 INT, ip32 INT)
RETURNS INT UNSIGNED DETERMINISTIC
RETURN (ip8 * 16777216 + ip16 * 65536 + ip24 * 256 + ip32);

-- Listing of datasources to use
CREATE TABLE IF NOT EXISTS Datasources
(id             INT NOT NULL AUTO_INCREMENT
,subscription   INTEGER NOT NULL
,name           VARCHAR(255) NOT NULL DEFAULT "New Datasource"
,ar_active      TINYINT(1) NOT NULL DEFAULT 0
,ar_interval    INT NOT NULL DEFAULT 300
,CONSTRAINT `PK_sds` PRIMARY KEY (`id`)
);

-- User Settings
CREATE TABLE IF NOT EXISTS Settings
(subscription   INTEGER PRIMARY KEY
,datasource     INT NOT NULL
,live_dest      INT DEFAULT NULL
,color_node     INT UNSIGNED NOT NULL DEFAULT 0x5555CC
,color_bg       INT UNSIGNED NOT NULL DEFAULT 0xAAFFDD
,color_tcp      INT UNSIGNED NOT NULL DEFAULT 0x5555CC
,color_udp      INT UNSIGNED NOT NULL DEFAULT 0xCC5555
,color_label    INT UNSIGNED NOT NULL DEFAULT 0x000000
,color_label_bg INT UNSIGNED NOT NULL DEFAULT 0xFFFFFF
,color_error    INT UNSIGNED NOT NULL DEFAULT 0x996666
,CONSTRAINT `FK_sds` FOREIGN KEY (`datasource`) REFERENCES `Datasources` (`id`)
,CONSTRAINT `FK_sld` FOREIGN KEY (`live_dest`) REFERENCES `Datasources` (`id`)
);

-- Look-Up-Table for ports and port aliases
CREATE TABLE IF NOT EXISTS Ports
(port              INT UNSIGNED NOT NULL PRIMARY KEY
,protocols         TEXT
,name              VARCHAR(10) NOT NULL DEFAULT ""
,description       VARCHAR(255) NOT NULL DEFAULT ""
);
